### ISSUE TITLE
Add JSON as optional format for sending activity events via MQTT

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sos#262]
As of v6.1.1 user activity data (connection open/close, session start/stop), are sent as MQTT messages in a plain text string format.
This makes it harder than necessary for receiving systems to use the data coming from Butler SOS.

Add second option where data is sent as JSON instead.
Keep the old method for backwards compatibility.

Add config file setting to control which topic to use for the JSON data:

```yaml
Butler-SOS:
  userEvents:
    sendToMQTT:
      topic: qliksense/userevent
      postTo:
        jsonTopic: true
```

This would post JSON data to `qliksense/userevent/json`
