### ISSUE TITLE
Refactor user activity events sent via MQTT

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sos#263]
Current model (v6.1.1) is not very flexible, simply because MQTT was never a major use case.
That has changed over the years and Butler SOS + MQTT is today probably one of the more robust ways of getting user activity info out from QSEoW to 3rd party systems.

The MQTT module of Butler SOS should thus be improved. 

> ⚠️ NOTE: This will be a breaking change.
> * The config file format will change
> * The structure of outgoing MQTT messages will change. For example, JSON field names will be all lower case with underscore as separator.

Things will as always be controlled from the config file:

```yaml
Butler-SOS:
  userEvents:
    sendToMQTT: 
      enable: true
      postTo:
        everythingTopic: 
          enable: true
          topic: qliksense/userevent
        sessionStartTopic:
          enable: true
          topic: qliksense/userevent/session/start
        sessionStopTopic:
          enable: true
          topic: qliksense/userevent/session/stop
        connectionOpenTopic:
          enable: true
          topic: qliksense/userevent/connection/open
        connectionCloseTopic:
          enable: true
          topic: qliksense/userevent/connection/close
```
