### ISSUE TITLE
Add log event tags from config file to outgoing MQTT messages

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sos#264]
These tags should be part of MQYY messages, just as they are for user activity MQTT messages:

```yaml
Butler-SOS:
  logEvents:
    tags:
      - tag: env
        value: DEV
      - tag: foo
        value: bar

```
