### ISSUE TITLE
Fail to start when no server tags defined in config file

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sos#276]
**Describe the bug**
If the YAML config file does not contain any custom server tags in `Butler-SOS.serversToMonitor.serverTagsDefinition`, this results in an error when starting Butler SOS v7.0:

```
C:\tools\butler-sos-prod\src\globals.js:134
    config.get('Butler-SOS.serversToMonitor.serverTagsDefinition').forEach((entry) => {
                                                                  ^

TypeError: Cannot read properties of null (reading 'forEach')
    at Object.<anonymous> (C:\tools\butler-sos-prod\src\globals.js:134:67)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
...
```

**Expected behavior**

**Screenshots**

**Describe environment:**
- This error will happen on alla platforms/environments, OSs, Docker/native etc.
- Butler SOS v7.0

**Config file(s)**
This will cause the error to occur:

```yaml
Butler-SOS:
  ...
  serversToMonitor
    ...
    serverTagsDefinition: 
      
    # Sense Servers that should be queried for healthcheck data 
    servers:
      ...
```

While this don't cause any errors

```yaml
Butler-SOS:
  ...
  serversToMonitor
    ...
    serverTagsDefinition: 
      - server_group
      
    # Sense Servers that should be queried for healthcheck data 
    servers:
      ...
```
