### ISSUE TITLE
Error when publishing Qlik Sense metrics to Prometheus endpoint

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sos#422]
Butler SOS 9.0.2 + added New Relic features.

```
PROM: Error saving health data for Prometheus! Error: Added label "service" is not included in initial labelset: [
  'host',
  'server_name',
  'server_description',
  'user_session_virtual_proxy',
  'user_session_host'
]
```

Most likely caused by the New Relic code incorrectly modifying the metrics tags sent to Prometheus. 
New Relic config defines

```yaml
      attribute: 
        static:                 # Static attributes/dimensions to attach to the events sent to New Relic.
          - name: service
            value: butler-sos
          - name: environment
            value: prod
```

which is suspiciously similar to the errors reported around `service` and `environment` tags.
