### ISSUE TITLE
Unmatched server tags in sample YAML config file

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sos#438]
'server_type` used in one place, `server-type` in others in `production_template.yaml` file, https://github.com/ptarmiganlabs/butler-sos/blob/master/src/config/production_template.yaml

```yaml
    serverTagsDefinition: 
      - server_group
      - serverLocation
      - server_type
      - serverBrand

    # Sense Servers that should be queried for healthcheck data 
    servers:
      - host: <server1.my.domain>:4747        # Example: 10.34.3.45:4747
        serverName: <server1>
        serverDescription: <description>
        logDbHost: <host name as used in QLogs db>
        userSessions:
          enable: true
          # Items below are mandatory if userSessions.enable=true
          host: <server1.my.domain>:4243      # Example: 10.34.3.45:4243
          virtualProxies:
            - virtualProxy: /                 # Default virtual proxy
            - virtualProxy: /hdr              # "hdr" virtual proxy
            - virtualProxy: /sales            # "sales" virtual proxy
        serverTags:
          server_group: DEV
          serverLocation: Asia
          server-type: virtual
          serverBrand: Dell
```

### Discussed in https://github.com/ptarmiganlabs/butler-sos/discussions/424

<div type='discussions-op-text'>

<sup>Originally posted by **shaybit** July 14, 2022</sup>
Hi, I followed the documentation as much as I could and encountered error as decribed below:

1. I created the root folder(named butler-sos-docker) and its subfolders as described here : https://butler-sos.ptarmiganlabs.com/docs/getting_started/install/docker/
2. downloaded the config file from https://github.com/ptarmiganlabs/butler-sos/blob/master/src/config/production_template.yaml, named it production.yaml and moved it to butler-sos-docker/config/
3. Edited the config file and filled the necessary according the  page : https://butler-sos.ptarmiganlabs.com/docs/getting_started/setup/
4. Downloaded the docker file from : https://github.com/ptarmiganlabs/butler-sos/blob/master/docs/docker-compose/docker-compose_fullstack_influxdb.yml and named it docker-compose.yml and  changed only the NODE_ENV variable to be "NODE_ENV=production" since my config file name is productio
5. Added the qlik certificates to the butler-sos-docker/config/certificate folder
6. Enter the terminal to the root folder location and ran docker-compose up then I got the following error

butler-sos    | /nodeapp/node_modules/influx/lib/src/schema.js:83
butler-sos    |             throw new Error("Extraneous tags detected for writing InfluxDB point in " +
butler-sos    |                   ^
butler-sos    |
butler-sos    | Error: Extraneous tags detected for writing InfluxDB point in SenseOps.sense_server: `server-type`.
butler-sos    |     at Schema.checkTags (/nodeapp/node_modules/influx/lib/src/schema.js:83:19)
butler-sos    |     at InfluxDB.parsePoint (/nodeapp/node_modules/influx/lib/src/index.js:919:43)
butler-sos    |     at /nodeapp/node_modules/influx/lib/src/index.js:834:89
butler-sos    |     at Array.forEach (<anonymous>)
butler-sos    |     at InfluxDB.writePoints (/nodeapp/node_modules/influx/lib/src/index.js:833:16)
butler-sos    |     at Object.postHealthMetricsToInfluxdb (/nodeapp/src/lib/post-to-influxdb.js:208:10)
butler-sos    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
butler-sos    |
butler-sos    | Node.js v18.2.0
butler-sos exited with code 1

the docker ps command shows:

CONTAINER ID   IMAGE                             COMMAND                  CREATED          STATUS                             PORTS                                            NAMES
d5a759d3c7ac   ptarmiganlabs/butler-sos:latest   "docker-entrypoint.s…"   13 minutes ago   Up 20 seconds (health: starting)                                                    butler-sos
9ff371bbc1dc   grafana/grafana:latest            "/run.sh"                13 minutes ago   Up 20 seconds                      0.0.0.0:3000->3000/tcp                           grafana
a835a28b59d5   influxdb:1.8.10                   "/entrypoint.sh infl…"   13 minutes ago   Up 20 seconds                      0.0.0.0:8082->8082/tcp, 0.0.0.0:8086->8086/tcp   influxdb

Thanks for your assistance</div>
