### ISSUE TITLE
Add blacklist for user IDs to monitor

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sos#62]
The various system accounts are likely to be of less interest when tracking user sessions. 
Create a blacklist for user IDs that should be ignored.

**Comment by mountaindude** [comment]
Solution concept:

Add config file entry similar to this:

```yaml
...
  userSessions:
    enableSessionExtract: true          # Query unique user IDs of what users have sessions open (true/false)?
    pollingInterval: 30000                  # How often (milliseconds) should session data be polled?
    excludeUser:                                  # Optional blacklist of users that should be disregarded when it comes to session monitoring
      - directory: LAB
        userId: testuser1
      - directory: INTERNAL
        userId: sa_engine
      - directory: INTERNAL
        userId: sa_api
```
