### ISSUE TITLE
 TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by USBWAG** [ptarmiganlabs/butler-sos#624]
### What version of Butler SOS are you using?

App version: 9.6.2

### What version of Node.js are you using? Not applicable if you use the standalone version of Butler SOS.

Node version   : v14.20.1 | Node version   : v18.17.1

### What command did you use to start Butler SOS?

node src\butler-sos.js -c config file

### What operating system are you using?

Windows 10

### What CPU architecture are you using?

Intel(R) Core(TM) i5-10500 CPU

### What Qlik Sense versions are you using?

Qlik Sense May 2022 Patch 3

### Describe the Bug

Is not Update Health Metrics to InfluxDB Have try it in 3 Version of InfluxDB and 3 versions of butler-sos also 2 version of Nodejs
The Butler SOS Usage that will write it to the InfluxDB

I've tried various settings and always get the same result, so I think there's an error in the config file that I'm missing,
Could you give me a tip where there could possibly be a problem in the config if you see the error code?

Error in Node Version 14 
023-09-14T16:52:06.429Z verbose: HEALTH: Received ok response from <ServerName>
2023-09-14T16:52:06.445Z debug: HEALTH: "<!doctype html>\r\n<html ..........
2023-09-14T16:54:05.112Z debug: HEALTH: Calling HEALTH metrics Influxdb posting method
(node:19808) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substring' of undefined
    at getFormattedTime (c:\tools\butler-sos-9.6.2\src\lib\post-to-influxdb.js:13:22)
    at Object.postHealthMetricsToInfluxdb (c:\tools\butler-sos-9.6.2\src\lib\post-to-influxdb.js:45:27)
    at c:\tools\butler-sos-9.6.2\src\lib\healthmetrics.js:103:36
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Error in Node 18 

2023-09-14T17:18:05.652Z debug: HEALTH: URL=******
2023-09-14T17:18:05.733Z verbose: HEALTH: Received ok response from <ServerName>
2023-09-14T17:18:05.735Z debug: HEALTH: "<!doctype html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta name=\"robots\" content=\"noindex, nofollow\" />\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n    <title>Qlik Sense login page</title>\r\n    <meta charset=\"utf-8\">\r\n

2023-09-14T17:18:05.850Z debug: HEALTH: Calling HEALTH metrics Influxdb posting method
c:\tools\butler-sos-9.6.2\src\lib\post-to-influxdb.js:13
    const year = str.substring(0, 4);
                     ^

TypeError: Cannot read properties of undefined (reading 'substring')
    at getFormattedTime (c:\tools\butler-sos-9.6.2\src\lib\post-to-influxdb.js:13:22)
    at Object.postHealthMetricsToInfluxdb (c:\tools\butler-sos-9.6.2\src\lib\post-to-influxdb.js:45:27)
    at c:\tools\butler-sos-9.6.2\src\lib\healthmetrics.js:103:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1

### Expected Behavior

Write Data to the InfluxDB

### To Reproduce

I have now try it with Butler-SOS Version from 9.5.3 to 9.6.2  i got everytime the same Failer also i have try it with more versions of influxDB, i don't finde the Problem

**Comment by mountaindude** [comment]
Looks like a config error, I agree.
But even so, the error message you get could obviously be a bit better... Will see if I can do something about that.

You should def use Node 18, but even easier is prob to use the pre-compiled binaries. 
Unless you want to develop/tweak Butler SOS itself of course, then you need to get Node.js. working.

**Comment by mountaindude** [comment]
This log entry is a bit suspicious:

```
2023-09-14T17:18:05.735Z debug: HEALTH: "<!doctype html>\r\n<html lang="en">\r\n\r\n <meta name="robots" content="noindex, nofollow" />\r\n <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\r\n <title>Qlik Sense login page</title>\r\n <meta charset="utf-8">\r\n
```

It indicates that you are trying to pull info from a web page rather than an API.
Which in turn indicate that your authentication to Sense isn't working...


Butler SOS is only compatible with InfluxDB version 1.x. 
Support for 2.x etc coming.

**Comment by mountaindude** [comment]
What does your server definitions look like in the configuration file?

Here is mine. Important that you include the port 4243!

```yaml
    # Sense Servers that should be queried for healthcheck data
    servers:
      - host: pro2-win1.lab.ptarmiganlabs.net:4747    # Example: 10.34.3.45:4747
        serverName: sense1
        serverDescription: Central
        logDbHost: sense1
        userSessions:
          enable: true
          # Items below are mandatory if userSessions.enable=true
          host: 10.11.12.13:4243  
          virtualProxies:
            - virtualProxy: /                         # Default virtual proxy
            - virtualProxy: /sales                    # "sales" virtual proxy

```
