### ISSUE TITLE
Config visualisation is not obfuscating the IP of config visualisation host

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sos#869]
### What version of Butler SOS are you using?

10.2

### What version of Node.js are you using? Not applicable if you use the standalone version of Butler SOS.

-

### What command did you use to start Butler SOS?

-

### What operating system are you using?

-

### What CPU architecture are you using?

-

### What Qlik Sense versions are you using?

-

### Describe the Bug

The config file looks like this:

```yaml
Butler-SOS:
  ...
  # Should Butler SOS start a web server that serves an obfuscated view of the Butler SOS config file?
  configVisualisation:
    enable: true  
    host: localhost       # Hostname or IP address where the web server will listen. Should be localhost in most cases.
    port: 3100            # Port where the web server will listen. Change if port 3100 is already in use.
    obfuscate: true        # Should the config file shown in the web UI be obfuscated?
```

The value `Butler-SOS.host is not obfuscated`.

### Expected Behavior

Obfuscate the host in the same way as other host fields in the YAML config file.
