### ISSUE TITLE
Make key-value pairs have same naming convention across entire config file

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sos#890]
>  **This will be a breaking change as it involves changes to the existing config file format.**

# Now
Two formats are used:

```yaml
tags:
  - tag: env
    value: DEV
```

and 

```yaml
static:
  - name: metricType
    value: butler-sos-uptime
```

# Proposed change

Use `name` and `value` everywhere.
